### ISSUE TITLE
Gobliiins 1 EGA error when extracting graphics

### ISSUE THREAD

**Issue by Jerome-Labbe-RedArtGames** [adventurebrew/boozook#20]
Hello,

Many thanks for this incredible tool.
I have noticed an issue with the DOS EGA floppy version of Gobliiins 1 detected by ScummVM as ("intro.stk", "c65e9cc8ba23a38456242e1f2b1caad4", 135561).

Here is the error that is shown:

`NEGATIVE OFFSET
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\boozook-kTotGKg--py3.12\Scripts\\boozook", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Projects\Gob\GraphicsEditor\boozook-organize\src\boozook\runner.py", line 285, in main
    graphics.main(gamedir, args.rebuild, **advanced)
  File "E:\Projects\Gob\GraphicsEditor\boozook-organize\src\boozook\graphics.py", line 48, in main
    decode(game, patterns, target)
  File "E:\Projects\Gob\GraphicsEditor\boozook-organize\src\boozook\graphics.py", line 16, in decode
    parse(game, entry, target)
  File "E:\Projects\Gob\GraphicsEditor\boozook-organize\src\boozook\codex\ext.py", line 218, in parse
    raise ValueError('IM resource not implemented')
ValueError: IM resource not implemented`

It works without errors with the other Gob1 versions I tried.

Is this something you think that can be fixed ?

Thanks again.

**Comment by BJNFNE** [comment]
It looks like we did not implement the IM data yet.

**Comment by BJNFNE** [comment]
This would be large work to implement this. So it will take an while.

**Comment by BJNFNE** [comment]
@Jerome-Labbe-RedArtGames

**Comment by BLooperZ** [comment]
@Jerome-Labbe-RedArtGames Thank you, should now be fixed
